# Copyright 2022-2023 Chris Croome
#
# This file is part of the Webarchitects JMESPath Ansible role.
#
# The Webarchitects Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects JMESPath Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
variables:
  ANSIBLE_FORCE_COLOR: "1"
  GIT_STRATEGY: none
  MOLECULE_VERBOSITY: "0"
  PIPX_HOME: /opt
  PIPX_BIN_DIR: /usr/local/bin
  PY_COLORS: "1"
before_script:
  - cd
  - source ~/.profile
  - mkdir -p builds/${CI_PROJECT_ROOT_NAMESPACE}
  - cd builds/${CI_PROJECT_ROOT_NAMESPACE}
  - git clone ${CI_PROJECT_URL}.git
  - cd ${CI_PROJECT_NAME}
  # - which ansible
  # - ansible --version
  # - ansible-galaxy collection list
  # - which ansible-lint
  # - ansible-lint --version
  # - which molecule
  # - molecule --version
stages:
  - bookworm
  - bullseye
  - jammy
bookworm:
  image: registry.git.coop/webarch/containers/images/bookworm:20230605
  stage: bookworm
  script:
    - molecule converge
bullseye:
  image: registry.git.coop/webarch/containers/images/bullseye:20230605
  stage: bullseye
  script:
    - molecule converge
jammy:
  image: registry.git.coop/webarch/containers/images/jammy:20230605
  stage: jammy
  script:
    - molecule converge
...
