# Copyright 2022-2025 Chris Croome
#
# This file is part of the Webarchitects JMESPath Ansible role.
#
# The Webarchitects Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects JMESPath Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: JMESPath .deb present
  block:

    - name: Packages present when root
      block:

        - name: Packages present when root
          ansible.builtin.apt:
            pkg: "{{ jp_pkgs }}"
            update_cache: true
            state: present

        - name: GitHub binary absent when root
          ansible.builtin.file:
            path: /usr/local/bin/jp
            state: absent

      when: ansible_facts.effective_user_id == 0

    - name: Packages checked when not root
      block:

        - name: Use apt role local facts
          block:

            - name: Include apt role local fact tasks
              ansible.builtin.include_role:
                name: apt
                tasks_from: local_facts.yml
              when: ansible_facts.ansible_local.dpkg.installed is not defined

            - name: Check for the Debian packages when not root
              ansible.builtin.assert:
                that:
                  - jp_deb_pkg in ansible_facts.ansible_local.dpkg.installed
                fail_msg:
                  - "The {{ jp_deb_pkg }} is required"
                  - "You can install all the requirements using:"
                  - "sudo apt install{% for jp_pkg_missing in jp_pkgs %} {{ jp_pkg_missing }}{% endfor %}"
                quiet: "{% if ansible_verbosity == 0 %}true{% else %}false{% endif %}"
              loop: "{{ jp_pkgs }}"
              loop_control:
                loop_var: jp_deb_pkg

          when: jp_apt_role | bool

        - name: Use Ansible package facts
          block:

            - name: Read package facts
              ansible.builtin.package_facts:
                manager: apt

            - name: Check for the Debian packages when not root
              ansible.builtin.assert:
                that:
                  - jp_deb_pkg in ansible_facts.packages.keys()
                fail_msg:
                  - "The {{ jp_deb_pkg }} is required"
                  - "You can install all the requirements using:"
                  - "sudo apt install{% for jp_pkg_missing in jp_pkgs %} {{ jp_pkg_missing }}{% endfor %}"
                quiet: "{% if ansible_verbosity == 0 %}true{% else %}false{% endif %}"
              loop: "{{ jp_pkgs }}"
              loop_control:
                loop_var: jp_deb_pkg

          when: not jp_apt_role | bool

      when: ansible_facts.effective_user_id != 0

  tags:
    - jp
...
