---
- name: JMESPath Terminal present
  block:

    # https://github.com/jmespath/jmespath.terminal/issues/19#issuecomment-1156039074
    - name: Use pip to install an old version of setuptools
      ansible.builtin.pip:
        name: setuptools==57
        state: present

    - name: Use pip to install jpterm
      ansible.builtin.pip:
        name: jmespath-terminal
        state: present

  when: jp_term | bool
  tags:
    - jp

- name: JMESPath Terminal absent
  block:

    - name: Use pip to uninstall jpterm
      ansible.builtin.pip:
        name: jmespath-terminal
        state: absent

    - name: Use pip to uninstall an old version of setuptools
      ansible.builtin.pip:
        name: setuptools==57
        state: absent

  when: not jp_term | bool
  tags:
    - jp
...
