# Copyright 2022-2024 Chris Croome
#
# This file is part of the Webarchitects JMESPath Ansible role.
#
# The Webarchitects Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects JMESPath Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: Skip the JMESPath tasks
  ansible.builtin.debug:
    msg: "The tasks in the jp role are not being run as the jp variable is not set to true"
  when: not jp | bool

- name: JMESPath
  block:

    - name: Include JMESPath verify variables tasks
      ansible.builtin.include_tasks: verify.yml
      when: jp_verify | bool

    - name: Read package facts
      ansible.builtin.package_facts:
        manager: apt

    - name: Use Debian packages on Debian Bookworm and Trixie
      ansible.builtin.include_tasks: deb.yml
      when: ansible_facts.distribution_release is regex('^bookworm|trixie$')

    - name: Use GitHub binary when not running Debian Bookworm or Trixie
      ansible.builtin.include_tasks: bin.yml
      when: ansible_facts.distribution_release is not regex('^bookworm|trixie$')

    - name: Skip installing JMESPath Terminal
      ansible.builtin.debug:
        msg: "The jpterm tasks are being skipped as the jp_term variable is not set to true"
      when: not jp_term | bool

    - name: Install JMESPath Terminal Community
      ansible.builtin.include_tasks: jpterm_community.yml
      when:
        - jp_term is defined
        - jp_term | bool

  when: jp | bool
  tags:
    - jp
...
