# Copyright 2022-2023 Chris Croome
#
# This file is part of the Webarchitects JMESPath Ansible role.
#
# The Webarchitects Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects JMESPath Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: Verify as root
  become: true
  connection: local
  gather_facts: true
  hosts:
    - localhost
  tasks:

    - name: Initialize role without actually running it
      ansible.builtin.include_role:
        name: jp
        tasks_from: init

    - name: Check if /usr/bin/jp is present
      ansible.builtin.stat:
        path: /usr/bin/jp
      register: molecule_stat_usr_bin_jp

    - name: Run /usr/bin/jp -h
      ansible.builtin.command: /usr/bin/jp -h
      check_mode: false
      changed_when: false
      register: molecule_stat_usr_bin_jp_h
      when: molecule_stat_usr_bin_jp.stat.exists | bool

    - name: Debug the results of /usr/bin/jp -h
      ansible.builtin.debug:
        var: molecule_stat_usr_bin_jp_h.stdout_lines
      when: molecule_stat_usr_bin_jp_h.stdout is defined

    - name: Check if /usr/local/bin/jp is present
      ansible.builtin.stat:
        path: /usr/local/bin/jp
      register: molecule_stat_usr_local_bin_jp

    - name: Run /usr/local/bin/jp -h
      ansible.builtin.command: /usr/local/bin/jp -h
      check_mode: false
      changed_when: false
      register: molecule_stat_usr_local_bin_jp_h
      when: molecule_stat_usr_local_bin_jp.stat.exists | bool

    - name: Debug the results of /usr/local/bin/jp -h
      ansible.builtin.debug:
        var: molecule_stat_usr_local_bin_jp_h.stdout_lines
      when: molecule_stat_usr_local_bin_jp_h.stdout is defined

- name: Verify as user
  become: false
  connection: local
  gather_facts: true
  hosts:
    - localhost
  tasks:

    - name: Initialize role without actually running it
      ansible.builtin.include_role:
        name: jp
        tasks_from: init

    - name: Check if /home/ansible/.local/bin/jp is present
      ansible.builtin.stat:
        path: /home/ansible/.local/bin/jp
      register: molecule_stat_home_ansible_local_bin_jp

    - name: Run /home/ansible/.local/bin/jp -h
      ansible.builtin.command: /home/ansible/.local/bin/jp -h
      check_mode: false
      changed_when: false
      register: molecule_stat_home_ansible_local_bin_jp_h
      when: molecule_stat_home_ansible_local_bin_jp.stat.exists | bool

    - name: Debug the results of /home/ansible/.local/bin/jp -h
      ansible.builtin.debug:
        var: molecule_stat_home_ansible_local_bin_jp_h.stdout_lines
      when: molecule_stat_home_ansible_local_bin_jp_h.stdout is defined

...
