# Copyright 2022-2023 Chris Croome
#
# This file is part of the Webarchitects JMESPath Ansible role.
#
# The Webarchitects Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects JMESPath Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: Verify as root
  # become: true
  connection: local
  # gather_facts: true
  hosts:
    - localhost
  tasks:

    - name: Run which jp
      ansible.builtin.command: which jp
      check_mode: false
      changed_when: false
      register: molecule_root_which_jp

    - name: Debug which jp
      ansible.builtin.debug:
        var: molecule_root_which_jp.stdout

    - name: Run which jp -a
      ansible.builtin.command: which jp -a
      check_mode: false
      changed_when: false
      register: molecule_root_which_jp_a
      failed_when: molecule_root_which_jp_a.rc is not regex('^0|1$')

    - name: Check jp versions
      ansible.builtin.command: "{{ molecule_jp_path }} --version"
      check_mode: false
      changed_when: false
      register: molecule_jp_v
      loop: "{{ molecule_root_which_jp_a.stdout_lines }}"
      loop_control:
        loop_var: molecule_jp_path

    - name: Set facts for the jp versions
      ansible.builtin.set_fact:
        molecule_jp_root_versions: "{{ molecule_jp_v | community.general.json_query('results[].{path: molecule_jp_path, version: stdout_lines[0]}') }}"

    - name: Debug jp versions
      ansible.builtin.debug:
        var: molecule_jp_root_versions

    - name: Run which jpterm
      ansible.builtin.command: which jpterm
      check_mode: false
      changed_when: false
      register: molecule_root_which_jpterm

    - name: Debug which jpterm
      ansible.builtin.debug:
        var: molecule_root_which_jpterm.stdout

    - name: Run which jpterm -a
      ansible.builtin.command: which jpterm -a
      check_mode: false
      changed_when: false
      register: molecule_root_which_jpterm_a
      failed_when: molecule_root_which_jpterm_a.rc is not regex('^0|1$')

    - name: Check jpterm versions
      ansible.builtin.command: "{{ molecule_jpterm_path }} --version"
      check_mode: false
      changed_when: false
      register: molecule_jpterm_v
      loop: "{{ molecule_root_which_jpterm_a.stdout_lines }}"
      loop_control:
        loop_var: molecule_jpterm_path

    - name: Set facts for the jpterm versions
      ansible.builtin.set_fact:
        molecule_jpterm_root_versions: "{{ molecule_jpterm_v | community.general.json_query('results[].{path: molecule_jpterm_path, version: stdout_lines[0]}') }}"

    - name: Debug jpterm versions
      ansible.builtin.debug:
        var: molecule_jpterm_root_versions
...
